# permissions for end users to edit crs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-editor-role
rules:
- apiGroups:
  - tools.51talk.me
  resources:
  - crs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.51talk.me
  resources:
  - crs/status
  verbs:
  - get
