# permissions for end users to view crs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-viewer-role
rules:
- apiGroups:
  - tools.51talk.me
  resources:
  - crs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.51talk.me
  resources:
  - crs/status
  verbs:
  - get
