---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemo
  namespace: ddddd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxdemo
    spec:
      containers:
        - image: nginx:1.17.4-alpine
          imagePullPolicy: Always
          name: nginx
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 10Mi
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginxdemo