/*
Copyright 2021 The 51talk EFF.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/ysicing/cr/apis/tools/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCRs implements CRInterface
type FakeCRs struct {
	Fake *FakeToolsV1beta1
	ns   string
}

var crsResource = schema.GroupVersionResource{Group: "tools.51talk.me", Version: "v1beta1", Resource: "crs"}

var crsKind = schema.GroupVersionKind{Group: "tools.51talk.me", Version: "v1beta1", Kind: "CR"}

// Get takes name of the cR, and returns the corresponding cR object, and an error if there is any.
func (c *FakeCRs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.CR, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crsResource, c.ns, name), &v1beta1.CR{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CR), err
}

// List takes label and field selectors, and returns the list of CRs that match those selectors.
func (c *FakeCRs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.CRList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crsResource, crsKind, c.ns, opts), &v1beta1.CRList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.CRList{ListMeta: obj.(*v1beta1.CRList).ListMeta}
	for _, item := range obj.(*v1beta1.CRList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cRs.
func (c *FakeCRs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crsResource, c.ns, opts))

}

// Create takes the representation of a cR and creates it.  Returns the server's representation of the cR, and an error, if there is any.
func (c *FakeCRs) Create(ctx context.Context, cR *v1beta1.CR, opts v1.CreateOptions) (result *v1beta1.CR, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crsResource, c.ns, cR), &v1beta1.CR{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CR), err
}

// Update takes the representation of a cR and updates it. Returns the server's representation of the cR, and an error, if there is any.
func (c *FakeCRs) Update(ctx context.Context, cR *v1beta1.CR, opts v1.UpdateOptions) (result *v1beta1.CR, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crsResource, c.ns, cR), &v1beta1.CR{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CR), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCRs) UpdateStatus(ctx context.Context, cR *v1beta1.CR, opts v1.UpdateOptions) (*v1beta1.CR, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(crsResource, "status", c.ns, cR), &v1beta1.CR{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CR), err
}

// Delete takes name of the cR and deletes it. Returns an error if one occurs.
func (c *FakeCRs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(crsResource, c.ns, name), &v1beta1.CR{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCRs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.CRList{})
	return err
}

// Patch applies the patch and returns the patched cR.
func (c *FakeCRs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CR, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crsResource, c.ns, name, pt, data, subresources...), &v1beta1.CR{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CR), err
}
